version: '3'
services:
  devel:
    build: 
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        NO_PROXY: ""
        IMAGE_NAME: ubuntu
        IMAGE_TAG: 22.04
        PYTHON: python3.10
      context: ../
      dockerfile: ./docker/Dockerfile
      target: devel
    command: python tests/CI/test_config.py
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    image: yooodleee/Hello_Project/intel-extension-for-transformers:devel-1.4.0
    pull_policy: always
  prod:
    extends:
      services: devel
    build:
      target: devel
    image: yooodleee/Hello_Project/intel-extension-for-transformers:1.4.0
    volumes:
      - $PWD/..:/app
    working_dir: /app